---
title: "participant"
author: "Kaki"
date: "2018年5月29日"
output: github_document
---
```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
```

```{r}
participant <-read_csv("data/2013-2017 Bike MS Participants.csv")
```
```{r}
event <-read_csv("data/2013-2017 Bike Events.csv")
```

# What occupations were responsible for most of our fundraising?
```{r}
participant%>%
  filter(!is.na(`Participant Occupation`))%>%
  group_by(`Fiscal Year`,`Participant Occupation`)%>%
  summarise(ttl_dona = sum(`Total of All Confirmed Gifts($)`))%>%
  filter(rank(desc(ttl_dona))<=10)%>%
  ggplot()+
  geom_col(aes(x = `Fiscal Year`, y= ttl_dona , fill =`Participant Occupation` ), position = "dodge")+
  theme(legend.position="bottom", axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_fill_brewer(palette="Set3")



```


# What industries have had the strongest involvement in Bike MS in the last five years?

## record count
```{r}
participant%>%
  filter(!is.na(`Participant Occupation`))%>%
  group_by(`Fiscal Year`,`Participant Occupation`)%>%
  summarise(count_team = n())%>%
  filter(rank(desc(count_team))<=10)%>%
  ggplot()+
  geom_col(aes(x = `Fiscal Year`, count_team , fill =`Participant Occupation` ), position = "dodge")+
  theme(legend.position="bottom", axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_fill_brewer(palette="Set3")
```

## event_count
```{r}
participant%>%
  filter(!is.na(`Participant Occupation`))%>%
  group_by(`Fiscal Year`,`Participant Occupation`)%>%
  summarise(count_event = length(unique(`Event ID`)))%>%
  filter(rank(desc(count_event))<=8)%>%
  ggplot()+
  geom_col(aes(x = `Fiscal Year`, count_event , fill =`Participant Occupation` ), position = "dodge")+
  theme(legend.position="bottom", axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_fill_brewer(palette="Set3")
```

